# Generated by Django 3.1.6 on 2021-04-03 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnare_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.TextField(max_length=3000, verbose_name='Ответ')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='questionnare_app.poll', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'db_table': 'choices',
            },
        ),
    ]
